resources: ~

image:
  repository: ghcr.io/cloudfoundry/k8s/rep
  pullPolicy: IfNotPresent
  tag: ""

instanceIdentityCASecret: instance-identity

locket:
  address: locket.{{ .Release.Namespace }}.svc.cluster.local:8891
  certificateSecret: ""

bbsAddress: https://bbs.{{ .Release.Namespace }}.svc.cluster.local:8889
advertiseDomain: cell.127-0-0-1.nip.io
repAdvertiseDomain: ""
caCertificate: ~
containerProxyVerifySubjectAltName: 
  - "gorouter"
  - "ssh-proxy"

fileServer:
  address: http://fileserver.{{ .Release.Namespace }}.svc.cluster.local:8080

loggregator:
  apiHost: forwarder-agent.{{ .Release.Namespace }}.svc.cluster.local
  apiPort: 3458
  certificateSecret: ""

stacks:
  cflinuxfs4: ghcr.io/cloudfoundry/k8s/cflinuxfs4:1.304.0

workloadsNamespace: cf-workloads

pauseImage: registry.k8s.io/pause:3.10.2

nodeSelector:
  cloudfoundry.org/cell: "true"

tolerations:
  - key: cloudfoundry.org/cell
    operator: Equal
    value: "true"
    effect: NoSchedule
